version: "3.1"


services:
    flask-application:
        container_name: flask-app
        build:
            context: .
        command: gunicorn -b 0.0.0.0:8000 app:app --workers=5
        restart: always
        ports:
            - 80:8000