version: "3.1"

networks: 
    app-flask:
        driver: bridge
services: 
    vkbot:
        container_name: flask-app
        build:
            context: .
        command: python app.py
        restart: always
        networks: 
            - app-flask
        volumes: 
            - .:/src